[package]
name = "evolang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rayon = "1.8"
csv = "1.3.0"
libc = "0.2.150"
libloading = "0.8.1"

[build-dependencies]
bindgen = "0.69.1"